<div class="box coupon">
	<header class="box-head">
		<h2><?=$this->__('Discount Codes')?></h2>
	</header>
	<section class="box-content">
		<form id="discount-coupon-form" action="<?=$this->getUrl('checkout/cart/couponPost')?>" method="post">
			<label for="coupon_code"><?=$this->__('Enter your coupon code if you have one.')?></label>
			<input type="hidden" name="remove" id="remove-coupone" value="0">
			<div class="input-box">
				<input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?=$this->htmlEscape($this->getCouponCode())?>" placeholder="<?=$this->__('Enter code here...')?>">
			</div>
			<div class="buttons-set">
				<button type="button" title="<?=$this->__('Apply Coupon')?>" class="btn btn-apply" onclick="discountForm.submit(false)" value="<?=$this->__('Apply Coupon')?>">
					<em><em></em></em>
					<?=$this->__('Apply Coupon')?>
				</button>
				<?php if (strlen($this->getCouponCode())): ?>
					&nbsp;
					<button type="button" title="<?=$this->__('Cancel Coupon')?>" class="btn" onclick="discountForm.submit(true)" value="<?=$this->__('Cancel Coupon')?>">
						<em><em></em></em>
						<?=$this->__('Cancel Coupon')?>
					</button>
				<?php endif ?>
			</div>
		</form>
		<script>
		//<![CDATA[
		var discountForm = new VarienForm('discount-coupon-form');
		discountForm.submit = function (isRemove) {
			if (isRemove) {
				$('coupon_code').removeClassName('required-entry');
				$('remove-coupone').value = "1";
			} else {
				$('coupon_code').addClassName('required-entry');
				$('remove-coupone').value = "0";
			}
			return VarienForm.prototype.submit.bind(discountForm)();
		}
		//]]>
		</script>
	</section>
</div>