<div class="box shipping">
	<header class="box-head">
		<h2>
			<?=$this->__('Estimate Shipping and Tax')?>
		</h2>
	</header>
	<section class="box-content">
		<form action="<?=$this->getUrl('checkout/cart/estimatePost')?>" method="post" id="shipping-zip-form" class="no-margin">
			<p><?=$this->__('Enter your destination to get a shipping estimate.')?></p>
			<ul class="form-list">
				<li>
					<label for="country" class="required"><em>*</em><?=$this->__('Country')?></label>
					<div class="input-box">
						<?=Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId())?>
					</div>
				</li>
				<li>
					<label for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"'?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>'?><?=$this->__('State/Province')?></label>
					<div class="input-box">
						<select id="region_id" name="region_id" title="<?=$this->__('State/Province')?>" style="display:none;"<?=($this->isStateProvinceRequired() ? ' class="validate-select"' : '')?>>
							<option value=""><?=$this->__('Please select region, state or province')?></option>
						</select>
					   <script type="text/javascript">
					   //<![CDATA[
						   $('region_id').setAttribute('defaultValue',  "<?=$this->getEstimateRegionId()?>");
					   //]]>
					   </script>
					   <input type="text" id="region" name="region" value="<?=$this->escapeHtml($this->getEstimateRegion())?>"  title="<?=$this->__('State/Province')?>" class="input-text" style="display:none;">
				   </div>
				</li>

				<?php if ($this->getCityActive()): ?>
					<li>
						<label for="city"<?php if ($this->isCityRequired()) echo ' class="required"'?>><?php if ($this->isCityRequired()) echo '<em>*</em>'?><?=$this->__('City')?></label>
						<div class="input-box">
							<input class="input-text<?php if ($this->isCityRequired()): ?> required-entry<?php endif ?>" id="city" type="text" name="estimate_city" value="<?=$this->escapeHtml($this->getEstimateCity())?>">
						</div>
					</li>
				<?php endif ?>

				<li>
					<label for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"'?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>'?><?=$this->__('Zip/Postal Code')?></label>
					<div class="input-box">
						<input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()): ?> required-entry<?php endif ?>" type="text" id="postcode" name="estimate_postcode" value="<?=$this->escapeHtml($this->getEstimatePostcode())?>">
					</div>
				</li>
			</ul>
			<div class="buttons-set">
				<button type="button" title="<?=$this->__('Get Shipping Quote')?>" onclick="coShippingMethodForm.submit()" class="btn btn-quote">
					<em><em></em></em>
					<?=$this->__('Get Shipping Quote')?>
				</button>
			</div>
		</form>
		<script type="text/javascript">
		//<![CDATA[
			new RegionUpdater('country', 'region', 'region_id', <?=$this->helper('directory')->getRegionJson()?>);
		//]]>
		</script>

		<?php if (($shippingRateGroups = $this->getEstimateRates())): ?>
		<form id="co-shipping-method-form" action="<?=$this->getUrl('checkout/cart/estimateUpdatePost')?>">
			<dl class="sp-methods">
				<?php foreach ($shippingRateGroups as $code => $rates): ?>
					<dt><?=$this->escapeHtml($this->getCarrierName($code))?></dt>
					<dd>
						<ul>
						<?php foreach ($rates as $rate): ?>
							<li<?php if ($rate->getErrorMessage()) echo ' class="error-msg"' ?>>
							   <?php if ($rate->getErrorMessage()): ?>
									<?=$this->escapeHtml($rate->getErrorMessage())?>
							   <?php else: ?>
									<input name="estimate_method" type="radio" value="<?=$this->escapeHtml($rate->getCode())?>" id="s_method_<?=$rate->getCode()?>"<?php if ($rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"'?> class="radio">
									<label for="s_method_<?=$rate->getCode()?>"><?=$this->escapeHtml($rate->getMethodTitle())?>
									<?php $excl = $this->getShippingPrice($rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()) ?>
									<?php $incl = $this->getShippingPrice($rate->getPrice(), true) ?>
									<?=$excl ?>
									<?php if ($this->helper('tax')->displayShippingBothPrices() && $incl != $excl): ?>
										(<?=$this->__('Incl. Tax') ?> <?=$incl ?>)
									<?php endif ?>
									</label>
							   <?php endif?>
							</li>
						<?php endforeach ?>
						</ul>
					</dd>
				<?php endforeach ?>
			</dl>
			<div class="buttons-set">
				<button type="submit" title="<?=$this->__('Update Total')?>" class="btn" name="do" value="<?=$this->__('Update Total')?>"><span><span><?=$this->__('Update Total')?></span></span></button>
			</div>
		</form>
		<?php endif ?>
		<script>
		//<![CDATA[
			var coShippingMethodForm = new VarienForm('shipping-zip-form');
			var countriesWithOptionalZip = <?=$this->helper('directory')->getCountriesWithOptionalZip(true)?>;

			coShippingMethodForm.submit = function () {
				var country = $F('country');
				var optionalZip = false;

				for (i=0; i < countriesWithOptionalZip.length; i++) {
					if (countriesWithOptionalZip[i] == country) {
						optionalZip = true;
					}
				}
				if (optionalZip) {
					$('postcode').removeClassName('required-entry');
				}
				else {
					$('postcode').addClassName('required-entry');
				}
				return VarienForm.prototype.submit.bind(coShippingMethodForm)();
			}
		//]]>
		</script>
	</section>
</div>