<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()): ?>
<div class="block block-cart">
	<?php $cartQty = $this->getSummaryCount()?>
	<div class="block-title">
		<strong>
			<span>
				<?=$this->__('My Shopping')?>
				<em><?=$this->__('Cart')?></em>
			</span>
		</strong>
	</div>
	<div class="block-content">

		<?php if ($cartQty > 0): ?>
			<div class="summary">
				<?php if ($cartQty==1): ?>
					<p class="amount"><?=$this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart'))?></p>
				<?php else: ?>
					<p class="amount"><?=$this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $cartQty)?></p>
				<?php endif ?>
				<p class="subtotal">
					<?php if ($this->canApplyMsrp()): ?>
						<span class="map-cart-sidebar-total"><?=$this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER') ?></span>
					<?php else: ?>
						<span class="label"><?=$this->__('Cart Subtotal:')?></span> <?=Mage::helper('checkout')->formatPrice($this->getSubtotal())?>
						<?php if ($subtotalInclTax = $this->getSubtotalInclTax()): ?>
							<br>(<?=Mage::helper('checkout')->formatPrice($subtotalInclTax)?> <?=Mage::helper('tax')->getIncExcText(true)?>)
						<?php endif ?>
					<?php endif ?>
				</p>
			</div>
		<?php endif ?>

		<?php if ($cartQty and $this->isPossibleOnepageCheckout()): ?>
		<div class="actions">
			<?=$this->getChildHtml('extra_actions')?>
			<button type="button" title="<?=$this->__('Checkout')?>" class="btn btn-dark btn-checkout" onclick="setLocation('<?=$this->getCheckoutUrl()?>')">
				<em><em></em></em>
				<?=$this->__('Checkout')?>
			</button>
		</div>
		<?php endif ?>

		<?php if ($items = $this->getRecentItems() and count($items)): ?>
			<div class="recent-items">
				<p class="block-subtitle"><?=$this->__('Recently added item(s)')?></p>
				<ol id="cart-sidebar" class="mini-products-list">
					<?php foreach ($items as $item): ?>
						<?=$this->getItemHtml($item)?>
					<?php endforeach ?>
				</ol>
			</div>
		<?php else: ?>
			<p class="empty"><?=$this->__('You have no items in your shopping cart.')?></p>
		<?php endif ?>

	</div>
</div>
<?php endif ?>
