<div class="account-login">
	<header class="page-title">
		<h1><?=$this->__('Login or Create an Account')?></h1>
	</header>
	<?=$this->getMessagesBlock()->getGroupedHtml()?>
	<form action="<?=$this->getPostActionUrl()?>" method="post" id="login-form">
		<section class="login-section">
			<div class="login-column">
				<h2><?=$this->__('New Customers')?></h2>
				<p><?=$this->__('By creating an account with Industrial Evolution, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.')?></p>
			</div>

			<div class="login-column">
				<h2><?=$this->__('Registered Customers')?></h2>
				<p><?=$this->__('If you have an account with us, please log in.')?></p>
				<ul class="form-list">
					<li>
						<label for="email" class="required"><em>*</em><?=$this->__('Email Address')?></label>
						<div class="input-box">
							<input type="text" name="login[username]" value="<?=$this->htmlEscape($this->getUsername())?>" id="email" class="input-text required-entry validate-email" title="<?=$this->__('Email Address')?>">
						</div>
					</li>
					<li>
						<label for="pass" class="required"><em>*</em><?=$this->__('Password')?></label>
						<div class="input-box">
							<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?=$this->__('Password')?>">
						</div>
					</li>
					<?=$this->getChildHtml('form.additional.info');?>
					<?=$this->getChildHtml('persistent.remember.me');?>
				</ul>
				<?=$this->getChildHtml('persistent.remember.me.tooltip');?>
				<p class="required"><?=$this->__('* Required Fields')?></p>
			</div>
		</section>

		<section class="login-section">
			<div class="login-column">
				<div class="buttons-set">
					<button type="button" title="<?=$this->__('Create an Account')?>" class="btn" onclick="window.location='<?=Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl())?>';">
						<em><em></em></em>
						<?=$this->__('Create an Account')?>
					</button>
				</div>
			</div>

			<div class="login-column">
				<div class="buttons-set">
					<a href="<?=$this->getForgotPasswordUrl()?>" class="f-left"><?=$this->__('Forgot Your Password?')?></a>
					<button type="submit" class="btn" title="<?=$this->__('Login to My Acount')?>" name="send" id="send2">
						<em><em></em></em>
						<?=$this->__('Login to My Account')?>
					</button>
				</div>
			</div>
		</section>
	</form>
</div>