<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-account"><?php echo $this->__('Quote # %s', $quote['increment_id'] ? $quote['increment_id'] : $quote['quote_id']) ?>
		</h4>
	</div>
	<div class="fieldset">
		<table class="form-list" cellspacing="0">
			<tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Last update') ?></label></td>
                    <td class="value"><strong><?php echo $this->formatDate($quote['updated_at'], 'medium', true) ?></strong></td>
                </tr>
				<?php $status = $this->getStatusArray(); ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Quote Status') ?></label></td>
                    <td class="value"><strong><span id="quote_status"><u><?php echo strtolower($status[$quote['status']]); ?></u></span></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('RFQ From') ?></label></td>
                    <td class="value"><strong><?php echo $this->getStoreViewInfo($quote['store_id']); ?></strong></td>
                </tr>
                <?php $name = trim($this->getAdminName($quote['user_id']));?>
                <?php if(!empty($name)): ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Assigned to') ?></label></td>
                    <td class="value"><strong><?php echo $name; ?></strong></td>
                </tr>
                <?php endif; ?>
            </tbody></table>
	</div>
</div>