<?php

$item = $this->getItem();
$product = Mage::getModel('catalog/product')
			   ->setStoreId($item->getOrder()->getStoreId())
			   ->load($item->getProductId());
?>
<tr>
	<td align="center" valign="top" style="font-size:11px; padding:3px 9px;">
		<img src="<?=Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(80, 50)?>" alt="<?=$this->htmlEscape($item->getName())?>" />
	</td>
	<td align="left" valign="top" style="font-size:11px; padding:3px 9px;">
		<strong><?=$this->htmlEscape($item->getName())?></strong>
		<?php if ($this->getItemOptions()): ?>
		<dl style="margin:0; padding:0;">
			<?php foreach ($this->getItemOptions() as $option): ?>
			<dt><strong><em><?=$option['label']?></em></strong></dt>
			<dd style="margin:0; padding:0 0 0 9px;"><?=nl2br($option['value'])?></dd>
			<?php endforeach ?>
		</dl>
		<?php endif ?>
		<?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
		<?php if ($addInfoBlock) :?>
			<?=$addInfoBlock->setItem($item->getOrderItem())->toHtml();?>
		<?php endif ?>
		<?=$this->htmlEscape($item->getDescription())?>
	</td>
	<td align="left" valign="top" style="font-size:11px; padding:3px 9px;"><?=$this->htmlEscape($this->getSku($item))?></td>
	<td align="center" valign="top" style="font-size:11px; padding:3px 9px;"><?=$item->getQty()*1?></td>
</tr>
