<?php

$orders = $this->getOrders();
?>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<div class="page-title">
	<h1><?=$this->__('My Orders')?></h1>
</div>
<?=$this->getPagerHtml() ?>
<?php if ($orders->getSize()):?>
	<table class="table table-bordered table-striped" id="my-orders-table">
		<thead>
			<tr>
				<th><?=$this->__('Order #')?></th>
				<th><?=$this->__('Date')?></th>
				<th><?=$this->__('Ship To')?></th>
				<th><span class="nobr"><?=$this->__('Order Total')?></span></th>
				<th><span class="nobr"><?=$this->__('Order Status')?></span></th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php $odd = '' ?>
			<?php foreach ($orders as $order):?>
				<tr>
					<td><?=$order->getRealOrderId()?></td>
					<td><span class="nobr"><?=$this->formatDate($order->getCreatedAtStoreDate())?></span></td>
					<td><?=$order->getShippingAddress() ? $this->htmlEscape($order->getShippingAddress()->getName()) : '&nbsp;'?></td>
					<td><?=$order->formatPrice($order->getGrandTotal())?></td>
					<td><em><?=$order->getStatusLabel()?></em></td>
					<td class="a-center">
						<span class="nobr"><a href="<?=$this->getViewUrl($order)?>"><?=$this->__('View Order')?></a>
							<?php /*<span class="separator">|</span><a href="<?=$this->getTrackUrl($order)?>"><?=$this->__('Track Order')?></a>&nbsp;*/?>
							<?php if ($this->helper('sales/reorder')->canReorder($order)) :?>
							<span class="separator">|</span> <a href="<?=$this->getReorderUrl($order)?>" class="link-reorder"><?=$this->__('Reorder')?></a>
						<?php endif ?>
						</span>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else:?>
	<p><?=$this->__('You have placed no orders.') ?></p>
<?php endif?>
