<?php

$order = $this->getOrder();
$items = $order->getItemsCollection();
$index = 0;
$count = $items->count();
?>
<table class="table table-bordered" id="my-orders-table">
	<thead>
		<tr>
			<th><?=$this->__('Product Name')?></th>
			<th><?=$this->__('SKU')?></th>
			<th class="a-right"><?=$this->__('Price')?></th>
			<th class="a-center"><?=$this->__('Qty')?></th>
			<th class="a-right"><?=$this->__('Subtotal')?></th>
		</tr>
	</thead>

	<?php foreach ($items as $item): ?>
		<?php if ($item->getParentItem()) continue ?>
		<tbody>
			<?=$this->getItemHtml($item)?>
			<?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $item) and $item->getGiftMessageId()): ?>
				<tr class="border<?=($index++ > $count ?' last':'')?>" id="order-item-gift-message-<?=$item->getId()?>" style="display:none;">
					<?php $giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($item) ?>
					<td class="gift-message-row" colspan="7">
						<a href="#" title="<?=$this->__('Close')?>" onclick="return giftMessageToogle('<?=$item->getId()?>');" class="btn-close"><?=$this->__('Close')?></a>
						<dl class="gift-message">
							<dt><strong><?=$this->__('From:')?></strong> <?=$this->htmlEscape($giftMessage->getRecipient())?></dt>
							<dt><strong><?=$this->__('To:')?></strong> <?=$this->htmlEscape($giftMessage->getSender())?></dt>
							<dd><?=$this->helper('giftmessage/message')->getEscapedGiftMessage($item)?></dd>
						</dl>
					</td>
				</tr>
			<?php endif ?>
		</tbody>
	<?php endforeach ?>

	<tfoot>
		<?=$this->getChildHtml('order_totals')?>
	</tfoot>
</table>