<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="Content-Type" content="<?=$this->getContentType()?>">
<title><?=$this->getTitle()?></title>
<meta name="description" content="<?=htmlspecialchars($this->getDescription())?>">
<meta name="keywords" content="<?=htmlspecialchars($this->getKeywords())?>">
<meta name="robots" content="<?=htmlspecialchars($this->getRobots())?>">
<meta name="viewport" content="width=device-width">
<link rel="icon" href="<?=$this->getFaviconFile()?>" type="image/x-icon">
<link rel="shortcut icon" href="<?=$this->getFaviconFile()?>" type="image/x-icon">
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?=$this->helper('core/js')->getJsUrl('blank.html')?>';
    var BLANK_IMG = '<?=$this->helper('core/js')->getJsUrl('spacer.gif')?>';
//]]>
</script>
<![endif]-->
<?=$this->getCssJsHtml()?>
<?=$this->getChildHtml()?>
<?=$this->helper('core/js')->getTranslatorScript()?>
<?=$this->getIncludes()?>