<?php

$shipment = $this->getShipment();
$order    = $this->getOrder();
?>
<?php if ($shipment and $order and $shipment->getAllTracks()): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
	<thead>
		<tr>
			<th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?=$this->__('Shipped By')?></th>
			<th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?=$this->__('Tracking Number')?></th>
		</tr>
	</thead>
	<tbody>
	<?php $i=0; foreach ($shipment->getAllTracks() as $item): $i++ ?>
		<tr <?=$i%2?'bgcolor="#F6F6F6"':''?>>
			<td align="left" valign="top" style="padding:3px 9px"><?=$item->getTitle()?></td>
			<td align="center" valign="top" style="padding:3px 9px"><?=$item->getNumber()?></td>
		</tr>
	<?php endforeach ?>
	</tbody>
</table>
<?php endif ?>
