<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>

<div class="block block-cart block-quote">
	<?php $_quoteQty = $this->getQuoteQty() ?>
	<div class="block-title">
		<strong>
			<?=$this->__('My')?>
			<em><?=$this->__('Quote')?></em>
		</strong>
	</div>
	
	<div class="block-content">
	<?php if ($_quoteQty>0): ?>
		<div class="summary">
			<?php if ($_quoteQty==1): ?>
				<p class="amount"><?=$this->__('There is <a href="%s">1 item</a> in your quote.', $this->getUrl('qquoteadv/index/'))?></p>
			<?php else: ?>
				<p class="amount"><?=$this->__('There are <a href="%s">%s items</a> in your quote.', $this->getUrl('qquoteadv/index/'), $_quoteQty)?></p>
			<?php endif ?>
		     
		</div>
		<div class="actions">
		 <button type="button" title="<?=$this->__('Submit Quote')?>" class="button" onclick="setLocation('<?=Mage::getUrl('qquoteadv/index/');?>')"><span><span><?=$this->__('Submit Quote')?></span></span></button>
	</div>
	<p class="block-subtitle"><?=$this->__('Recently added item(s)')?></p>
		<ol id="cart-sidebar" class="mini-products-list">
	<?php foreach( $this->getQuote() as $item){         
	    $product = $this->getProduct($item->getProductId());
	    $quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute());
	foreach($quoteByProduct->getAllItems() as $_item) {
		$_item->setId($item->getId());  
		if( $_item->getProductId() == $product->getId() ) {
	    echo $this->getItemHtml($_item);        
		}
		}
		 } 
	 ?>
	</ol>
	<?php else: ?>
		<p class="empty"><?=$this->__('You have no items in your quote.')?></p>
	<?php endif ?>
	</div>
</div>

