<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
	<div class="block block-list block-viewed">
		<div class="block-title">
			<strong>
				<?=$this->__('Recently')?>
				<em><?=$this->__('Viewed')?></em>
			</strong>
		</div>
		<div class="block-content">
			<ol id="recently-viewed-items">
				<?php foreach ($_products as $_item): ?>
					<li class="item">
						<p class="product-name">
							<a href="<?=$this->getProductUrl($_item)?>">
								<?=$this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name')?>
							</a>
						</p>
					</li>
				<?php endforeach ?>
			</ol>
		</div>
	</div>
<?php endif ?>
