<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if ($this->getCollection()->getSize()): ?>
<div class="toolbar">
	<div class="pager">

		<p class="amount">
			<?php if ($this->getLastPageNum()>1): ?>
				<?=$this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum())?>
			<?php else: ?>
				<strong><?=$this->__('%s Item(s)', $this->getTotalNum())?></strong>
			<?php endif ?>
		</p>

		<?=$this->getPagerHtml()?>

		<div class="limiter">
			<label class="is-inline"><?=$this->__('Show')?></label>
			<select onchange="setLocation(this.value)" class="input-small is-inline no-margin">
			<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
				<option value="<?=$this->getLimitUrl($_key)?>"<?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif?>>
					<?=$_limit?>
				</option>
			<?php endforeach ?>
			</select> <?=$this->__('per page')?>
		</div>

	</div>

	<?php if ($this->isExpanded()): ?>
	<div class="sorter">
	
		<div class="sort-by">
			<label class="is-inline"><?=$this->__('Sort By')?></label>
			<select onchange="setLocation(this.value)" class="input-small no-margin">
			<?php foreach ($this->getAvailableOrders() as $_key=>$_order): ?>
				<option value="<?=$this->getOrderUrl($_key, 'asc')?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif ?>>
					<?=$this->__($_order)?>
				</option>
			<?php endforeach ?>
			</select>
			<?php if ($this->getCurrentDirection() == 'desc'): ?>
				<a href="<?=$this->getOrderUrl(null, 'asc')?>" title="<?=$this->__('Set Ascending Direction')?>"><img src="<?=$this->getSkinUrl('images/catalog/category/view/toolbar/down.png')?>" alt="<?=$this->__('Set Ascending Direction')?>" class="v-middle"></a>
			<?php else: ?>
				<a href="<?=$this->getOrderUrl(null, 'desc')?>" title="<?=$this->__('Set Descending Direction')?>"><img src="<?=$this->getSkinUrl('images/catalog/category/view/toolbar/up.png')?>" alt="<?=$this->__('Set Descending Direction')?>" class="v-middle"></a>
			<?php endif ?>
		</div>
	</div>
	<?php endif ?>
</div>
<?php endif?>
