<div class="block block-subscribe">
	<div class="block-title">
		<strong><span><?=$this->__('Newsletter')?></span></strong>
	</div>
	<form action="<?=$this->getFormActionUrl()?>" method="post" id="newsletter-validate-detail">
		<div class="block-content">
			<div class="form-subscribe-header">
				<label for="newsletter"><?=$this->__('Sign Up for Newsletter:')?></label>
			</div>
			<div class="input-box">
				<input type="text" name="email" id="newsletter" title="<?=$this->__('Sign up for the latest news, offers & discounts!')?>" class="input-text input-small input-block-level required-entry validate-email" placeholder="<?=$this->__('e.g. steve@example.com')?>">
			</div>
			<div class="actions">
				<button type="submit" title="<?=$this->__('Subscribe Now!')?>" class="btn btn-dark">
					<em><em></em></em>
					<?=$this->__('Subscribe Now!')?>
				</button>
			</div>
		</div>
	</form>
	<script type="text/javascript">
	//<![CDATA[
		var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
	//]]>
	</script>
</div>
